### ISSUE TITLE
`test_meminfo` fails on Kernel 5.8.12. Fields FileHugePages and FilePmdMapped

### ISSUE THREAD

**Issue by Nukesor** [eminence/procfs#102]
In this commit, two new fields have been added to `/proc/meminfo`:
https://github.com/torvalds/linux/commit/60fbf0ab5da1c360e02b7f7d882bf1c0d8f7e32a

The fields are `FileHugePages` and `FilePmdMapped`.

From what it looks like the Change has been added in v5.4-rc1, since it pops up in the diff from v5.4 and v5.4-rc1.

However, I'm not exactly sure what their purpose is, since I'm not that deep into kernel development and the commit messages are pretty nondescript...

**Comment by eminence** [comment]
Yeah, I've also not been able to find much about these new fields.  But I've added them to the `MemInfo` struct anyway
