### ISSUE TITLE
Permission denied for write-only files.

### ISSUE THREAD

**Issue by phiresky** [eminence/procfs#118]
`procfs::sys::vm::drop_caches(procfs::sys::vm::DropCache::All)` fails for me with "Permission denied" (even when running as root as needed). The reason I think is that that file cannot be read (`sudo cat /proc/sys/vm/drop_caches` shows the same error), only written to (`echo 3 |  sudo tee /proc/sys/vm/drop_caches` works).

**Comment by phiresky** [comment]
The following works correctly:

```rs
std::fs::OpenOptions::new()
            .read(false)
            .write(true)
            .open("/proc/sys/vm/drop_caches")?
            .write_all(b"3")?;
```

**Comment by eminence** [comment]
Nice catch, thanks!
