### ISSUE TITLE
Allow reading from specific pid's /net/dev

### ISSUE THREAD

**Issue by zz85** [eminence/procfs#126]
Seems like it should be an easy change to extend reading from /net/dev to specific processes

https://github.com/eminence/procfs/blob/d8f16ddc97413ab2fb38d23149be188ad0b750a7/src/net.rs#L619

eg.

`/proc/self/net/dev`

`/proc/<pid>/net/dev`

**Comment by eminence** [comment]
Yup, agreed.  Note that `/proc/net` is normally just a symlink to `/proc/self/net`.

I'm curious: what's your use-case to read the `/proc/net/dev` of a specific process?

**Comment by zz85** [comment]
I was planning to monitor bandwidth (bytes send/recv) usage for processes, and was thinking that /proc/net would be a place i could implemented it with...
