### ISSUE TITLE
inode size is not correct on x86_64

### ISSUE THREAD

**Issue by rc-grey** [eminence/procfs#130]
Currently inodes are defined as [u32](https://github.com/eminence/procfs/blob/master/src/process/mod.rs#L609). While it may not be likely to occur on most systems the kernel will print an unsigned long format string which can support up to eight bytes of length - right now I believe this will cause the library to ~~panic~~ return an internal error.

Relevant links:
1. https://elixir.bootlin.com/linux/latest/source/include/uapi/asm-generic/int-l64.h#L30
2. https://elixir.bootlin.com/linux/latest/source/net/socket.c#L307

**Comment by rc-grey** [comment]
Will not cause library to panic - but return an internal error - thanks @eminence for clarifying.

**Comment by eminence** [comment]
The `i_ino` field is defined to be an "unsigned long":

https://elixir.bootlin.com/linux/latest/source/include/linux/fs.h#L633

In C, this is defined an an unsigned 32-bit number.  Similarly, the `%lu` printf specifier also means "unsigned long".  So I think that using a `u32` is OK for storing an inode.

**Comment by eminence** [comment]
Ah ha.  but hmmm:

`ULONG_MAX` on my system is indeed 8 bytes....

**Comment by eminence** [comment]
Ok yeah, let's change this into a `u64` 👍

**Comment by rc-grey** [comment]
@eminence Should be ready to review - in #132
