### ISSUE TITLE
Make flate2 as a optional dependencies/feature, current is only used to read /proc/config.gz

### ISSUE THREAD

**Issue by pymongo** [eminence/procfs#156]
In many Rust projects which using procfs, mostly not use kernel_config() API

e.g. tikv project not use procfs::kernel_config()

I hope procfs's default feature is:

```
[features]
default = ["chrono", "kernel_config"]
```

let user to determine whether enable flate2 dependency

Can I write a PR for it?

**Comment by eminence** [comment]
Hi,

This is a good idea.  Actually I added this feature last month, but forgot to push and make a PR.  I just opened the the PR.  Can you take a look to see if it looks OK to you?

**Comment by pymongo** [comment]
resolve in #157
