### ISSUE TITLE
Remove dev dependency with `failure`

### ISSUE THREAD

**Issue by tatref** [eminence/procfs#221]
Hi,

Today, CI does not pass because of `object` release 0.30, that requires a recent compiler.

```
├── failure v0.1.8
│   ├── backtrace v0.3.67
│   │   ├── object v0.30.0
```

Here are the release notes (https://github.com/gimli-rs/object/commit/ed03e05213421e74ba2ccd216efe0ca0e8e06d65):
* The minimum supported rust version for the `read` feature has changed to 1.52.0.
* The minimum supported rust version for the `write` feature has changed to 1.61.0.

Also, `failure` is deprecated since 2020, they recommend to use `anyhow` or `thiserror`

`failure` is only used to test the functions signatures when they return `Result` for composition

How could we improve the situation?

**Comment by eminence** [comment]
It's getting increasingly hard to maintain the 1.48 MSRV in procfs.  I've just opened #222 to try to fix this particular issue.  I've also opened #223 to track the topic of MSRV for procfs
