### ISSUE TITLE
Possible vulnerability

### ISSUE THREAD

**Issue by vlad9486** [eminence/procfs#227]
Please, consider this [report](https://www.openwall.com/lists/oss-security/2022/12/21/6).

**Comment by eminence** [comment]
procfs is doing the right thing by [looking for the right paren](https://github.com/eminence/procfs/blob/ff5832ea3c5d07075e12b0019c4bc1458c330edd/src/process/stat.rs#L259), so we don't have any problems parsing stat files that spaces in the comm name, or internal parens (or other weird characters)
