### ISSUE TITLE
Fails to build on FreeBSD

### ISSUE THREAD

**Issue by yurivict** [eminence/procfs#228]
```
[procfs 0.14.2] Building procfs on an for a unsupported platform. Currently only linux and android are supported
[procfs 0.14.2] (Your current target_os is freebsd)
error: failed to run custom build command for `procfs v0.14.2`
```

**Comment by eminence** [comment]
Hi, procfs doesn't support FreeBSD, as this error message indicates.   So normally any project that depends on procfs would add it as a platform-specific dependency.   Is there something about the above error message that is not sufficiently clear?  Or something other behavior that you would expect?

**Comment by yurivict** [comment]
Thanks for the clarification.
