### ISSUE TITLE
PID should be u32

### ISSUE THREAD

**Issue by tatref** [eminence/procfs#245]
Hi,

PID is currently i32:

https://github.com/eminence/procfs/blob/3d5c9fa43b4e9f4401de4de71328401efe9ecd1a/src/process/mod.rs#L957

However, in stdlib, PID is u32: https://doc.rust-lang.org/std/process/fn.id.html

Is there any reason for this?

**Comment by eminence** [comment]
I think it's because there are a few procfs fields that can return `-1` (if the pid isn't available or something).   I can't name these fields off the top of my head, but it would be good to find them and document them.

**Comment by eminence** [comment]
Based on the notes in #250, we're keeping pid as `i32`
