### ISSUE TITLE
Please publish `procfs-core`

### ISSUE THREAD

**Issue by Jake-Shadle** [eminence/procfs#273]
Hey, we would really appreciate a release of `procfs-core` (see https://github.com/rust-minidump/minidump-writer/pull/80) when you have the time. For now I'll just move us back to `procfs` to cut a release.

**Comment by eminence** [comment]
Hey, I've just published an RC for both procfs and [procfs-core](https://crates.io/crates/procfs-core/)

There's a few doc changes I want to make before a non-RC release, but I don't think there will be many API changes, if at all.  I'm assuming you won't want to release your own crate with an RC dependency, so I'll target to get 0.16.0 published by the end of the week

**Comment by Jake-Shadle** [comment]
The fact it's an RC is not a deal-breaker, this removes the block on our own release which is sufficient for the short term. Thanks for the update!
