### ISSUE TITLE
[Bug] `FDsIter` memory leak

### ISSUE THREAD

**Issue by cyqsimon** [eminence/procfs#287]
### TLDR

There seems to be a memory leak out of `FDsIter`. When used in a hot path, leaked memory quickly accumulates to gigabyte sizes and even triggers OOM crashes.

### More details

This is the initial bug report: imsnif/bandwhich#284. Flamegraph and heaptrack data available there.

This is where the leak occurs out of bandwhich, according to heaptrack: https://github.com/imsnif/bandwhich/blob/4a27da5d5627c7eff0ac8c17c6c031db1879b6d1/src/os/linux.rs#L16.

It seems to be caused by [rustix::fs::Dir::read_from](https://docs.rs/rustix/latest/rustix/fs/struct.Dir.html#method.read_from) here:

https://github.com/eminence/procfs/blob/e8e9bc101840378d42119076eec5b5a721a446b2/procfs/src/process/mod.rs#L478

We have also tested both gnu and musl builds and saw the same problem. So we are no longer suspecting an allocator fault at this point.

### Reproducibility

It does not seem like this issue is reproducible on all Linux distros, but several users have reported this problem so it's unlikely to be bogus. So far we have the following datapoints:

| Problem seen on  | Problem not seen on |
|------------------|---------------------|
| Ubuntu 22.04 LTS | EndeavourOS         |
| Void Linux       |                     |

I'll populate the table some more as information comes in.

### Versions tested

- 0.15.1
- newest master (e8e9bc1)

**Comment by cyqsimon** [comment]
I haven't submitted an issue in `rustix` yet because it's not our direct dependency, and I would like to hear what `procfs` maintainers would like to say first. However I'm happy to do so if requested.

**Comment by cyqsimon** [comment]
@konnorandrews was able to track down this issue to a problem in `rustix` in https://github.com/imsnif/bandwhich/issues/284#issuecomment-1754321993. I have reported it as a vulnerability in `rustix`.

I will keep this issue open, but there is no action required from `procfs` for now.

**Comment by eminence** [comment]
Nice investigative work @konnorandrews and @cyqsimon.   If you have it, can you link the rustix issue?  It will be useful to following the evolution of the issue, and to know if procfs needs to bump a dependency to get the fix.  Thanks!

**Comment by eminence** [comment]
Thanks for the link.   No need for me to get early access, I can find out the details when the rest of the world does :)

**Comment by sigmaSd** [comment]
I can't reproduce on archlinux, @cyqsimon did you try it on one of the affected distro?,  this all would be easier if one could reproduce the issue

**Comment by cyqsimon** [comment]
Hello again, the fix has been released and backported to all affected minor versions of rustix (0.35.15, 0.36.16, 0.37.25, 0.38.19).

**Comment by eminence** [comment]
Thank you everyone, for the initial report, for the investigation, and for the fix.  This was an excellent demonstration of the value and the power of Open Source.  The minimum rustix version has been bumped to 0.38.19
