### ISSUE TITLE
Improve the ProcError

### ISSUE THREAD

**Issue by vorner** [eminence/procfs#29]
Hello

I've noticed the ProcError doesn't implement `std::error::Error`, nor does it implement `Display`. This is annoying, because it can't be directly used with common error handling strategies (eg. can't be used as `Box<dyn Error + Send + Sync>` or with `failure`).

Furthermore, the `NotFound` variant is not very explaining about *what* was not found, which makes tracking the origin of the error or the cause a bit harder :-(.

Is it possible to improve the error type?

Thank you

**Comment by eminence** [comment]
Good suggestions.

Regarding the `NotFound` variant, this can be raised if we think that a certain file should exist (basically anything under `/proc`, like `/proc/self/maps`), but this file doesn't exist.   If you know what function returned this error, generally the docs for that function should say that file it's trying to read.

What if the `NotFound` variant included the a PathBuf to the thing it was trying to open?  Would that be helpful? 

Also, Implementing `Error` and `Display` is a good idea, I'll do that (or a PR would be welcome if you wanted to do it)

**Comment by vorner** [comment]
>  If you know what function returned this error, generally the docs for that function should say that file it's trying to read.

I as the programmer might track that down, using the source code and the docs. But an administrator reading through logs where it ended up as a warning or some other user might have hard time.

> What if the NotFound variant included the a PathBuf to the thing it was trying to open? Would that be helpful?

Yes, definitely.
