### ISSUE TITLE
Is 0.4.7 supposed to be yanked from `crates.io`?

### ISSUE THREAD

**Issue by ErichDonGubler** [eminence/procfs#31]
Trying to access the [commit for 0.4.7](https://docs.rs/crate/procfs/0.4.7/source/.cargo_vcs_info.json) after a fresh clone results in:

```
$ git checkout 151a9bcfb9896082d83fbe72c3333f17002713e9                                                                                        
fatal: reference is not a tree: 151a9bcfb9896082d83fbe72c3333f17002713e9

$ git fetch origin 151a9bcfb9896082d83fbe72c3333f17002713e9
error: Server does not allow request for unadvertised object 151a9bcfb9896082d83fbe72c3333f17002713e9
```

Since there's no `CHANGELOG.md` to speak of, and there's [no notes on the 0.4.7 release](https://github.com/eminence/procfs/releases/tag/v0.4.7) that's [in `crates.io`](https://crates.io/crates/procfs/0.4.7), I don't want to make a guess as to which commit in currently available history I could develop against with PRs like https://github.com/eminence/procfs/pull/30. Is there a reason that this history isn't available right now? Was some history rewriting done, perhaps?

**Comment by eminence** [comment]
Sorry about that.  This is my fault.  I created the 0.4.7 release, but I forgot to push it to github.  I then merged some commits into master.  So the history is a little strange, but this commit (and the 0.4.7 tag) is now available on github.    

Sorry for the confusion.

**Comment by ErichDonGubler** [comment]
No problem, and thank you! I appreciate the super prompt response. :)
