### ISSUE TITLE
pressure info

### ISSUE THREAD

**Issue by brndnmtthws** [eminence/procfs#40]
It would be sweet to have pressure data from `/proc/pressure`.

See https://lwn.net/Articles/759781/ for details.

**Comment by eminence** [comment]
Looks neat, we should add support for this.  It seems my debian kernel isn't new enough to have this feature, so it might take me a bit to get a VM that supports this.    If anyone wants to take a stab at this, please feel free!

**Comment by idanski** [comment]
Hey @eminence I'll try to do it this weekend.
Any pointers as to how do you see the API?

**Comment by eminence** [comment]
Thanks @idanski !

I haven't dug into the documentation deeply, but seems like the data seems to be of this form:

```
    some avg10=70.24 avg60=68.52 avg300=69.91 total=3559632828
    full avg10=57.59 avg60=58.06 avg300=60.38 total=3300487258
```

If they only/always have these 4 fields, then maybe something like:

```rust

struct MemoryPressure {
    some: PressureData,
    full: PressureData
}

struct PressureData {
    avg10: f32,
    avg60: f32,
    avg300: f32,
    total: i32
}
```

**Comment by idanski** [comment]
@eminence :+1:  pretty much what I had in mind, I'll send a PR when I have something reviewable.
