### ISSUE TITLE
Turn procfs into a panic-free library

### ISSUE THREAD

**Issue by eminence** [eminence/procfs#44]
In the current design of the procfs crate, panics were possible, as assertions and unwraps are common in the code.  This was done to help uncover bugs in the library.

As the library has matured a bit, all of the assertions and unwraps should be replaced with `Result` types.  Most functions already return a `ProcResult`, so this itself isn't a big change to the public API of procfs.  

See also #39

**Comment by eminence** [comment]
I have a WIP pull request that implements this.  If you're interested in getting a peek at the code, please feel free to take a look.  I hope to have a new version published on crates.io within 1 or 2 weeks.  Please note that this will be a breaking change, so the new version number will be `v0.6.x`.

**Comment by idanski** [comment]
Thanks! I'll have a look sometime this week! Cheers!
