### ISSUE TITLE
Panic:  Internal Unwrap Error: No /proc/ directory: Too many open files (os error 24))

### ISSUE THREAD

**Issue by Chaz6** [eminence/procfs#63]
The below is what was outputted to my terminal:-

```
thread 'display_handler' panicked at 'called `Result::unwrap()` on an `Err` value: InternalError(bug at /home/chaz/.cargo/registry/src/github.com-1ecc6299db9ec823/procfs-0.7.7/src/process.rs:2066 (please report this procfs bug)
                                                                      
Internal Unwrap Error: No /proc/ directory: Too many open files (os error 24))', src/libcore/result.rs:1165:5
    stack backtrace:
        0:     0x55bd538b9174 - <unknown>
        1:     0x55bd538db12c - core::fmt::write::h4931d127ae5abcb3
        2:     0x55bd538b53c7 - <unknown>
        3:     0x55bd538bb6ce - <unknown>
        4:     0x55bd538bb3d1 - <unknown>
        5:     0x55bd538bbdc5 - std::panicking::rust_panic_with_hook::hfe88d534155928a4
        6:     0x55bd538bb962 - <unknown>
        7:     0x55bd538bb856 - rust_begin_unwind
        8:     0x55bd538d7aca - core::panicking::panic_fmt::h5e35aad6e23afea1
        9:     0x55bd538d7bc7 - core::result::unwrap_failed::hfa40973353787c4a
        10:     0x55bd537343c9 - <unknown>
        11:     0x55bd5371662d - <unknown>
        12:     0x55bd5374aef5 - <unknown>
        13:     0x55bd538bf91a - __rust_maybe_catch_panic
        14:     0x55bd5372e4f2 - <unknown>
        15:     0x55bd538af83f - <unknown>
        16:     0x55bd538bec80 - <unknown>
        17:     0x7f767a37be65 - <unknown>
        18:     0x7f7679e8e88d - clone
        19:                0x0 - <unknown>
```

(edited by @eminence to improve formatting)

**Comment by eminence** [comment]
Thanks for the report!  Can you say what application you using when you got this panic?

**Comment by eminence** [comment]
Hey @imsnif I'm just guessing that this might be from bandwhich (just based on the thread name `display_handler`).   

This panic is triggered from this line in procfs:

```rust
for dir in expect!(std::fs::read_dir("/proc/"), "No /proc/ directory") { /* ... */ }
```

The "too many open files" error makes be think that probably this isn't a procfs issue, but I don't know if it's because bandwhich is opening too many FDs, or something else.   

Any thoughts?

**Comment by imsnif** [comment]
Hmm... I can imagine extreme situations where this would happen. @Chaz6, could you share with us a little about your use case? What were you doing in your terminal when this happened?

**Comment by Chaz6** [comment]
Hiya, sorry for the delay. Yes, it is from `bandwhich` (formerly `what`). I just installed it (`cargo install what`) and ran `sudo $(which what)`.

**Comment by imsnif** [comment]
cool :) What platform are you using? Does this happen every time? If you do `ls /proc`, what do you get?

**Comment by Chaz6** [comment]
The host is CentOS 7.7.1908 64bit, and yes it happens every time. `ls /proc` shows all the usual proc files and folders (358 entries). On a different centos host it works normally.

**Comment by eminence** [comment]
This issue hasn't had much activity in a while, and I think the root issue might be with bandwhich, so I'm going to close this issue.  But please let me know if you think there's something procfs can do to help here.
