### ISSUE TITLE
Consider refactoring the project into smaller files

### ISSUE THREAD

**Issue by cjbassi** [eminence/procfs#66]
First off, I just want to say that this project looks great and I think we over at [rust-psutil](https://github.com/rust-psutil/rust-psutil) will probably switch to using this instead of doing our own custom procfs stuff.

One thing I think would be nice is if some of the larger files were refactored into smaller and more modular files, just to make things easier and more manageable to work with. For example, process.rs is over 3,000 lines.

**Comment by eminence** [comment]
Hi, and thanks!     I'm happy to help with any changes to make it easier to integrate with `rust-psutil`.

You are certainly right that some of the files have grown rather large (including process.rs).   Is your concern related to any specific problems (like how easy it it to make contributions, or how the docs are laid out, etc), or is it just a general concern about good development practices :smile:

**Comment by cjbassi** [comment]
Just general concern about good development practices :) Maybe the larger files could be refactored into sub modules where each struct gets its own file or something like that.

**Comment by eminence** [comment]
I'm going to close this, since the biggest offender (process.rs) has been split up.  This is something to keep in mind in general going forward.
