### ISSUE TITLE
Returning ticks in CpuTime

### ISSUE THREAD

**Issue by eminence** [eminence/procfs#76]
Hello,
The time returned in procfs::CpuTime should be a number of ticks in u64 as it is for processes in procfs::process::Stat. It's better to be able to get the values as returned by the kernel.

_Originally posted by @lparcq in https://github.com/eminence/procfs/issues/69#issuecomment-632280841_

**Comment by eminence** [comment]
I think this is a good idea, and wanted to open a dedicated to discuss it.

I do think that being able to get the time in seconds is useful.  Maybe we could also provide some methods that would do the tick-to-second conversion

**Comment by lparcq** [comment]
Yes it would be convenient to provide a helper function to convert in seconds. However I would prefer a number of milliseconds as u64 than a floating number of seconds.
