### ISSUE TITLE
Child processes

### ISSUE THREAD

**Issue by Nukesor** [eminence/procfs#78]
Hi!

First of all, thanks for providing this library! I'm currently looking for a nice solution to get all child processes of a specific process. After looking at `psutil` and `procfs`, I found that `procfs` is a lot cleaner and definitely better documented! Your library certainly deserves more attention :)

I would like to add the feature for `Process::children()` and it would be awesome to get a short introduction or a few tips on how to approach this.

Another thing I'm thinking about is, whether it should only be `Process::children_ids()` plus another function `Process::children()`, which actually returns a vector of `Process`.

**Comment by Nukesor** [comment]
This would definitely work :)
I just thought, that it would be more convenient to directly use the proc(5) feature for children.
This doesn't require iterating through all processes and allows instant lookup:
```
      /proc/[pid]/task/[tid]/children (since Linux 3.5)
              A space-separated list of child tasks of this task.  Each
              child task is represented by its TID.

              This option is intended for use by the checkpoint-restore
              (CRIU) system, and reliably provides a list of children only
              if all of the child processes are stopped or frozen.  It does
              not work properly if children of the target task exit while
              the file is being read!  Exiting children may cause non-exit‐
              ing children to be omitted from the list.  This makes this
              interface even more unreliable than classic PID-based
              approaches if the inspected task and its children aren't
              frozen, and most code should probably not use this interface.

              Until Linux 4.2, the presence of this file was governed by the
              CONFIG_CHECKPOINT_RESTORE kernel configuration option.  Since
              Linux 4.2, it is governed by the CONFIG_PROC_CHILDREN option.
```

Do you see an problems with such an helper function?
Could backwards compatibility for Linux `<3.5` become a problem?

**Comment by Nukesor** [comment]
There's also this nice [post](https://lwn.net/Articles/475688/), which explains why they added the feature. (Before that, the only approach to get child processes was exactly as you described above)

**Comment by Nukesor** [comment]
Ok. Nevermind, I obviously haven't read the full documentation.
`and most code should probably not use this interface.`

I completely omitted this part.

**Comment by eminence** [comment]
Ahh, yes it's tempting to use that `/children` file, but I do believe that the recommended way to get process children is to iterate over all processes.

For completeness, I think procfs should eventually add some functions to interface with with the `[pid]/task/[tid]/children` file (since it's a goal of procfs to cover everything in `/proc`), but it wouldn't be the recommended way to list child processes for general use.

Independently of that, procfs should also have some documentation and/or examples about how to get a list of child processes.

If you're interested in working on any of this, let me know!  😀

**Comment by Nukesor** [comment]
I'm definitely interested on contributing, so I'll probably add an example for getting children of a process :)
