### ISSUE TITLE
subprocess based question

### ISSUE THREAD

**Issue by xd009642** [eminence/procfs#82]
So I'm working on tracing a process via ptrace and am aiming to capture when a child process execs a new process and then get the path to that executable via procfs. Now the first part I've done but the procfs part I've just started looking into. 

It appears I should be able to walk the process tree and from that get my spawned process but just wondering how easy it is to get the path to the executable which has been executed for a given subprocess?

**Comment by eminence** [comment]
Hi.  I'm not sure I fully understand, so my apologies if my questions are off base:

When you use ptrace to capture when a child process execs a subprocess, you should be able to directly learn the PID of the subprocess, correct?  If so, once you have the PID of the child, you can look up its executable via something like this:

```rust
let child = Process::new(pid).unwrap();
let exec = child.exe().unwrap();
```

Or are you trying to learn the PID of the child using procfs?

**Comment by xd009642** [comment]
So it might be down to my lack-of knowledge of how the proc filesystem works in Linux but I thought I'd have to look in `/proc/${parent_pid}/task/${spawned_pid}` to get the exe. Is the spawned PID also represented in `/proc/${spawned_pid}`?

**Comment by eminence** [comment]
No,  In the  `/proc/$parent/task/` directory is an entry for each thread in $parent, not each subprocess.  (Also note that tasks/threads are not currently supported by this procfs library yet).

> Is the spawned PID also represented in `/proc/${spawned_pid}`?

Yup, that's correct.

**Comment by xd009642** [comment]
Okay that makes sense and `child.exe()` answers my other question so I'll close this and come back if I have any other questions in future. Thanks :+1:
