### ISSUE TITLE
Is ProcResult really nessesary?

### ISSUE THREAD

**Issue by tvannahl** [eminence/procfs#9]
After playing around with `procfs` (great start btw!) I just began asking myself if the type `ProcResult` is really nessesary the way it is?

The alternative I would think of is to use the regular `Result` type. That way everyone has functions like `expect()`, `is_err()`, `unwrap_or()`, … natively at hand.

I would find a definition like the following more ergonomic:

```rust
pub enum ProcError {
  PermissionDenied,
  NotFound,
}

type Result<T> = std::result::Result<T, ProcError>;

// example
fn f() -> Result<Process> {
  Err(ProcError::NotFound)
}
```

This is simillar to the way `Result` is used by `std::io`

**Comment by eminence** [comment]
I think you're right about this.  To be honest, I can't remember why I invented a new result type.  But not having the standard Result function alone is worth making the change.  I'll happily accept a PR for this (otherwise I'll make the change myself in about a week)
