### ISSUE TITLE
u32 conversion error on /proc/stat::procs_blocked

### ISSUE THREAD

**Issue by htejun** [eminence/procfs#94]
I have a program which periodically reads system usage stats from procfs and am very occasionally hitting the following.
```
[ WARN] report: Failed to update 1s usages (Internal error: bug at /home/htejun/.cargo/registry/src/github.com-1ecc6299db9ec823/procfs-0.7.9/src/lib.rs:901 (please report this procfs bug)
```
On 0.7.9, this is the line which reads procs_blocked from /proc/stat. The failure is transient and I have no idea how this could happen.

**Comment by eminence** [comment]
Hi, thank you for the bug report!

If you print out the error, it should have little more details about the problem.  I think you are printing it, but just haven't captured it in the text in your issue.  For example, given some code like this:

```rust
if let Err(e) = KernelStats::new() {
    println!("Error from KernelStats: {}", e);
}
```

You might see something like this in case of an error:

```
Error from KernelStats: Internal error: bug at src/lib.rs:901 (please report this procfs bug)
Internal Unwrap Error: Failed to parse &line[10..] ("ked 0") as a u32: invalid digit found in string
```

Do you think you can capture this second line of the error?

**Comment by htejun** [comment]
Ah, yes, it was right on the next line.
```
Internal Unwrap Error: Failed to parse &line[14..] ("18446744073709551615") as a u32: number too large to fit in target type)
```
which is 0xffffffffffffffff, so the kernel underflowed the blocked counting and printed -1 as `%lu`. I'll investigate what's going on w/ the kernel. Thank you.

**Comment by eminence** [comment]
What kernel are you running?

This could possibly be solved within the procfs crate-- since the `procs_blocked` field is an `Option`, it could be set to `None` if there is a parsing error (like in your case).

**Comment by htejun** [comment]
It turned out to be a recent change in the scheduler code. Reported to the subsystem maintainer / patch author. It should get fixed soon. Thanks.

http://lkml.kernel.org/r/20200918172759.GA4247@mtj.thefacebook.com

**Comment by eminence** [comment]
Thank you for the followup!
